version: '3'

services:
  web:
    build: .
    volumes:
      - ./php/:/var/www/html/
    ports:
      - '8000:80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: football
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 1234
    ports:
      - '9906:3306'
